flow:
  url: "https://labs.google/fx/vi/tools/flow"
  wait_timeout: 300  # seconds
  retry_attempts: 3
  retry_delay: 5

video:
  default_duration: 60  # seconds
  scene_duration: 8
  aspect_ratio: "16:9"
  quality: "1080p"
  format: "mp4"

gemini:
  model: "gemini-2.0-flash-exp"
  temperature: 0.7
  max_tokens: 8192

browser:
  headless: false
  viewport:
    width: 1920
    height: 1080
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"

paths:
  cookies: "./config/cookies.json"
  scripts: "./data/scripts"
  videos: "./data/videos"
  logs: "./data/logs"
